version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:16.20.2
    steps:
      - checkout
      - run:
          name: "fail"
          command: yarn install && yarn jest

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-case:
    jobs:
      - say-hello
